cache:
  - c:\cargo\registry

init:
  - mkdir c:\cargo
  - mkdir c:\rustup
  - SET PATH=c:\cargo\bin;%PATH%

clone_folder: c:\projects\wallpaper-changer

environment:
  CARGO_HOME: "c:\\cargo"
  RUSTUP_HOME: "c:\\rustup"
  CARGO_TARGET_DIR: "c:\\projects\\wallpaper-changer\\target"
  global:
    PROJECT_NAME: wallpaper-changer
    RUST_BACKTRACE: full
  matrix:
    - TARGET: i686-pc-windows-gnu
      CHANNEL: stable
      BITS: 32
      MSYS2: 1
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: stable
      BITS: 64
      MSYS2: 1

matrix:
  fast_finish: true

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MSYS2 set PATH=C:\msys64\mingw%BITS%\bin;%PATH%
  - rustc -V
  - cargo -V

build_script:
  - cargo build --release
artifacts:
  - path: target\release\*.exe
    name: exe
